### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by PencilShavings** [JupiterBroadcasting/jupiterbroadcasting.com#361] opened 2022-08-31 01:59 UTC
Visiting http://jupiterbroadcasting.com returns `404 page not found`.

**Comment by suorcd** [comment] 2022-08-31 03:49
I can reproduce this

```bash
$ curl -I https://jupiterbroadcasting.com/
HTTP/2 404 
date: Wed, 31 Aug 2022 03:48:44 GMT
content-type: text/plain; charset=utf-8
content-length: 19
x-content-type-options: nosniff
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ZF6USUhAUFA3ReN09lHFcdpVcyUyQ3NN8jQ3TGedN%2B8ITQ6bM1ybYUbb7%2B5yTxwy2PFAlOPK9dm54pgOLomYOy9HJuDXcZ4jGMyrNRmGFB6Vf5p2C8sN4EbcbuTfvCFC6Vae%2Bq9RAn9AZQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7432cad29d40c6cd-SEA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by PencilShavings** [comment] 2022-08-31 07:30
The site is reachable using the www subdomain. The redirect from just the base domain is either broken or not setup.

**Comment by elreydetoda** [comment] 2022-08-31 13:11
Yep, this is happening because of [this](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/358), trying to get it resolved with [this](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/358#issuecomment-1232918182)

**Comment by suorcd** [comment] 2022-08-31 21:26
The page appears to redirect properly.

**Comment by gerbrent** [comment] 2022-09-01 02:34
Appears resolved.. closing!

**Closed by gerbrent** 2022-09-01 02:34 UTC
Labels: bug, JB - action needed, infrastructure
