### ISSUE TITLE
Plausible analytics blocked by Ublock origin

### ISSUE THREAD

**Issue by domw95** [JupiterBroadcasting/jupiterbroadcasting.com#538] opened 2023-03-31 14:00 UTC
### Feature Description

Sorry not sure which issue template to use for this.

Plausible analytics currently points to https://plausible.ktz.cloud/js/plausible.js, which is blocked by default by ublock origin (/plausible.js$from=~plausible.io filter on the EasyPrivacy list), and possibly others.

I know this is only a temporary setup, but you can use https://plausible.ktz.cloud/js/script.js for the same script and it won't be blocked, if that is desirable.

**Comment by reclaimingmytime** [comment] 2023-03-31 23:11
This has been brought up before in the Matrix chat. The script name hasn't been changed, because this would go going against the user's conscious decision to block trackers. Tracking blockers are a feature, not a bug.

**Comment by elreydetoda** [comment] 2023-04-01 01:51
Yep, like @reclaimingmytime mentioned it's a feature :upside_down_face: 

I'm going to close this out, but feel free to comment more @domw95 or re-open if you think this deserves more attention. I believe it's JB's stance (through Alex (from Self-Hosted)) that they'd like Plausible to be caught by ad-blockers.

If you'd like to allow JB's plausible instance to track you I just figured out how to make a filter to whitelist that specific tracker on the JB website :slightly_smiling_face: 

If you follow these steps:

![image](https://user-images.githubusercontent.com/10230166/229259731-be8032e4-63a2-4b5d-b47b-b88e70b0e82f.png)

Then paste the following filter under the "My filters" tab on the uBlock Origin dashboard:
```
@@||plausible.ktz.cloud/js/plausible.js$script,domain=www.jupiterbroadcasting.com
```

You can tell if it works by opening up the uBlock Origin logger on jupiterbroadcasting.com:
![image](https://user-images.githubusercontent.com/10230166/229259948-424fbb8e-ba23-4718-b9f2-8b35fddb5585.png)

Click the refresh button and it should show you a green entry instead of a red one (like the cloudflare beacons).
![image](https://user-images.githubusercontent.com/10230166/229259905-0cc35fdc-a534-4265-8f19-91f2b6996ee8.png)

I figured out the syntax by doing the following:
![image](https://user-images.githubusercontent.com/10230166/229260118-ce3a9df1-d57c-4ecd-815d-721b505ad50d.png)

3 - is when I changed from block to allow

**Closed by elreydetoda** 2023-04-01 01:51 UTC
Labels: bug
