### ISSUE TITLE
LAN - "Episode Name | Show Name EP#" title formatting incorrect on card

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#67] opened 2022-07-09 21:13 UTC
* LAN cards feature title repeating as `Show Name EP# | Show Name EP#`. 
* Other shows have a distinct Episode Name as `"Episode Name | Show Name EP#" `
* LAN does not follow this unique episode naming convention in addition to it's EP#, thus the repetition.

Would be cleaner visually to only list `Show Name EP#` once on LAN cards.

![image](https://user-images.githubusercontent.com/7018928/178122638-6556faed-6c83-4c5e-988d-316984db01ed.png)

Compare to other episode/show cards:
![image](https://user-images.githubusercontent.com/7018928/178122621-1cdc47b5-d359-40f0-942e-7651a2174ea4.png)

**Comment by kbondarev** [comment] 2022-07-10 01:31
So this is an interesting one and could be solved in different ways that would mean different things.

LAN technically follows the same patterns as all the other episodes, like you wrote:
“Episode Name | Show Name EP#”

The issue is that for LAN, the episodes are named like this: “Linux Action News Ep#”

Hence the duplication. It’s a lot weird and confusing in case of LAN.

Possible Solutions:
1) Change the name of each episode to just the episode number. The implication of this probably would be that the episode name in the RSS feed would also be different, and hence in the apps.  Which I’m not sure whether it would be the desired result.
Here’s how it looks like right now in podcast app:
![779C2FE3-5EBA-41E9-BE92-9003FD8D7574](https://user-images.githubusercontent.com/7744333/178127760-076f4cbe-f09b-4c18-80d3-2bcdcb660c80.jpeg)


2) Leave the “episode_name” parameter as is and only treat it with an exception on the site.

3) In my opinion best solution is:
leave everything as is. But just remove the part “ | Show Name “ of each episode title. When you’re on the show’s page you know which show you’re at. When you’re on the home page which displays multiple shows - the header image already has the name of the show. I’d just maybe make sure to have the alt attributes and title attributes of the <img> have both the name of the show.

**Comment by gerbrent** [comment] 2022-07-10 02:44
Option 3: @kbondarev can you elaborate/clarify?

## Question 1: 
So you're proposing, if I understand:
* remove the `| Show Name` part of `Episode Name | Show Name EP#`  = `Episode Name EP#`

Thus each episode of LAN would then looks like "Linux Action News 247 247" ? I'm sure that's not what you mean, but just = `Episode Name` ie. "Linux Action News 247"

## Question 2:
And where in code would this change be done for only LAN? not likely in the scraper. In the /content/lan/epXXX.md ? But... perhaps not, as we don't want to change the metadata. Hmm...

I agree completely that Option 1 is not good - we want to keep the metadata 100% intact for who-knows-why-in-the-future.

**Comment by Webtron18** [comment] 2022-07-10 12:42
I forked the directory and have been trying to get a test site up to test my idea, but...

**Idea**:
We could add a conditional to the episode/preview that looks for duplicate title/show ep naming. I am not sure if Hugo can do this but I was trying to test it. Basically something like below (this is pseudo code since I am still learning). 

in `themes/jb/layouts/partials/episode/preview.html`

```
...

  <div class="card-content">
     <div class="content">
      <a href="{{ .Permalink }}"><h3>{{.Title}} 
          {{if ne {{.Title}} ({{.CurrentSection.Title}} {{.Params.episode}}) }} 
            | {{.CurrentSection.Title}} {{.Params.episode}} }}</h3></a>
          {{end}}

...
```

It would essentially check to see if the `{{Title}}` is the same as `{{.CurrentSection.Title}} {{.Params.episode}}` and ignore it. This would only output `{{Title}}` to the card in this case. 
Might also future proof it for another new show...

**Comment by Lord0fBytes** [comment] 2022-07-10 16:08
OK, great. I was able to get the test site up and running on my server and played around with the design. I think I figured out the code to do what you want. This is what it looks like for me with the new conditional. 
(I cant get the CS to load properly, but this is what the bare content looks like)
<img width="699" alt="Screen Shot 2022-07-10 at 11 58 50 AM" src="https://user-images.githubusercontent.com/7501413/178152656-5598a168-588e-4133-9b8e-c331e4c82b87.png">


I can put in one of those newfangled Pull Requests for this (apologies if I do that wrong).

**Comment by kbondarev** [comment] 2022-07-10 18:00
> ## Question 1:
> So you're proposing, if I understand:
> 
> * remove the `| Show Name` part of `Episode Name | Show Name EP#`  = `Episode Name EP#`
> 
> Thus each episode of LAN would then looks like "Linux Action News 247 247" ? I'm sure that's not what you mean, but just = `Episode Name` ie. "Linux Action News 247"

Right, I guess I didn't think it through completely. What if we change the format to be like this: "EP#: Episode Name". That way it would look a little better for LAN. For example: "247: Linux Action News 247". 
 
> ## Question 2:
> And where in code would this change be done for only LAN? not likely in the scraper. In the /content/lan/epXXX.md ? But... perhaps not, as we don't want to change the metadata. Hmm...

The theme html template files.

---

In any case, @Lord0fBytes solution works and is pretty simple. Maybe I over-complicated things :smile:

**Comment by Lord0fBytes** [comment] 2022-07-10 18:20
It happens to all of us @kbondarev 😄
I figured that way too if they have a one off show with no special title it will still work and isn't hard coded for LAN.

**Comment by StefanS-O** [comment] 2022-07-10 19:13
@Lord0fBytes solution was good. merged it, closing it now :)

**Closed by StefanS-O** 2022-07-10 19:13 UTC

**Comment by gerbrent** [comment] 2022-07-11 23:44
agree all around - love this solution. Well done all!

@kbondarev I like to think you and I were partly responsible for providing inspiration ; )
