### ISSUE TITLE
[Coder Radio] Episodes 1-54 Missing

### ISSUE THREAD

**Issue by ghost** [JupiterBroadcasting/jupiterbroadcasting.com#222] opened 2022-08-05 12:04 UTC
I think this was mentioned in a show once regarding why these episodes aren't in Fireside (something about a migration from a different podcast hosting provider).

Looks like the audio files no longer exist on Libsyn (which looks like what was used prior) for these episodes, but the video does.

**Comment by ChanceM** [comment] 2023-09-09 07:25
WIP:
![localhost_1313_show_coder-radio_page_44_](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/11327907/4a2dca1e-7429-4b24-80ae-d7d8b231845e)

**Comment by ChanceM** [comment] 2023-09-09 07:31
@noblepayne @gerbrent Any issues with bringing CR 0-54 to the site? It won't be on podverse, but will have show notes and direct links to MP3, oog, and video

**Comment by reclaimingmytime** [comment] 2023-09-18 20:59
Duplicate of #154

**Comment by ChanceM** [comment] 2023-09-19 03:20
> Duplicate of #154 

This is not an archive show. There are some similar issues due to these items not being on fireside but far from a duplicate.

**Closed** 2024-01-14 21:39 UTC
