### ISSUE TITLE
media player: Consider Podverse embedded player

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#20] opened 2022-07-05 01:03 UTC
Consider using the [Podverse](https://podverse.fm) embedded player to enable/facilitate Podcasting 2.0 features such as boosts/v4v, clips, chapters, etc.

demo: https://podverse.fm/embed/player-demo

code: https://github.com/podverse/podverse-web/pull/820/files

### Value-4-value
> This widget connects to your WebLN compatible browser extension to allow you to send Bitcoin over the Lightning Network to content creators.

**Comment by kbondarev** [comment] 2022-07-12 03:13
Podverse developer Mitch, made this proposal on Matrix ([link to thread](https://matrix.to/#/!rDlEtonuSythLzmxQL:jupiterbroadcasting.com/$y8pw_bj_RV3BZwTmnMQtf_kUxRcU8IEiwOP0239Rc8Y?via=jupiterbroadcasting.com&via=matrix.org&via=0x6b.dev)):

> mdowney:
>
> 1) Create the JP page for the episode.
> 
> 2) Paste the Podverse embed code, and pass in URL param overrides for podcast title, enclosure url, episode title, episode pub date, and possibly an episode GUID, so it can render with that information immediately.
> 
> 2b) We would need to disable the on-click "open episode in Podverse" behaviors while the embed is using the overridden method. Chapters and the lightning icon would also be missing.
> 
> 3) Publish the JP episode page.
> 
> 4) When a visitor lands on the page, the embed will first check if an episode with that enclosure url (or episode GUID) already exists in our database. If no, then the embed renders with the override params. If yes, then it ignores the override params, and loads the full parsed data we have from the RSS feed.

> kiro:
>
> Oh that sounds cool :))
> Would the chapters and lightning icon be missing only when it can't find the episode in podverse database or all the time?

> mdowney:
>
> Only while it's not in our database. As long as the enclosure url and/or guid match, then it should be fully functional afterwards :)
> I'd go with GUID first actually, since that is more permanent

**Comment by kbondarev** [comment] 2022-07-15 05:52
Closing since pretty much a duplicate of #102

**Closed by kbondarev** 2022-07-15 05:52 UTC
Labels: duplicate, enhancement
